version: '3.8'

services:
  test:
    image: joroovb/node-web-app-arm
    container_name: testapp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    ports:
      - 8080:8080
    restart: unless-stopped
